# Generated by Django 5.1.6 on 2025-02-09 12:36

import candidate.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='RG')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Possui Deficiência')),
                ('disability_description', models.TextField(blank=True, null=True, verbose_name='Descrição da Deficiência')),
                ('has_drivers_license', models.BooleanField(default=False, verbose_name='Possui CNH')),
                ('is_first_job', models.BooleanField(default=False, verbose_name='Primeiro Emprego')),
                ('is_currently_employed', models.BooleanField(default=False, verbose_name='Atualmente Empregado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidate.utils.generate_image_path, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='DriversLicenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de CNH',
                'verbose_name_plural': 'Categorias de CNH',
                'db_table': 'drivers_license_category',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='candidate.candidate', verbose_name='Candidato')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Número de Telefone')),
                ('alternative_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefone Alternativo')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='candidate.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Informação de Contato',
                'verbose_name_plural': 'Informações de Contato',
                'db_table': 'contact_info',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='drivers_license_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='candidate.driverslicensecategory', verbose_name='Categoria da CNH'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.gender', verbose_name='Gênero'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network', to='candidate.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'db_table': 'social_network',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.state', verbose_name='Estado'),
        ),
    ]
