# Generated by Django 5.1.6 on 2025-02-09 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
                'db_table': 'area_of_interest',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'job_title',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Proficiência em Idioma',
                'verbose_name_plural': 'Proficiências em Idiomas',
                'db_table': 'language_proficiency',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='StatusResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status do Currículo',
                'verbose_name_plural': 'Status dos Currículos',
                'db_table': 'status_resume',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='candidate.candidate', verbose_name='Candidato')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('skills', models.ManyToManyField(to='resume.skill', verbose_name='Habilidades')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.statusresume', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('is_current', models.BooleanField(default=False, verbose_name='Está Trabalhando Atualmente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.company', verbose_name='Empresa')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.jobtitle', verbose_name='Cargo')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('is_current', models.BooleanField(default=False, verbose_name='Está Cursando Atualmente')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.course', verbose_name='Curso')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.institution', verbose_name='Instituição')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Educação',
                'verbose_name_plural': 'Educações',
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='ResumeLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.language', verbose_name='Idioma')),
                ('language_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.languageproficiency', verbose_name='Proficiência')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='resume.resume', verbose_name='Currículo')),
            ],
            options={
                'verbose_name': 'Idioma do Currículo',
                'verbose_name_plural': 'Idiomas dos Currículos',
                'db_table': 'resume_language',
            },
        ),
        migrations.CreateModel(
            name='SubareaOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('area_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.areaofinterest', verbose_name='Área de Interesse')),
            ],
            options={
                'verbose_name': 'Subárea de Interesse',
                'verbose_name_plural': 'Subáreas de Interesse',
                'db_table': 'subarea_of_interest',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='subareas_of_interest',
            field=models.ManyToManyField(to='resume.subareaofinterest', verbose_name='Subáreas de Interesse'),
        ),
    ]
