# Generated by Django 5.1.6 on 2025-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_end_date_alter_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Está deletado'),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Está cursando atualmente'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Está trabalhando atualmente'),
        ),
    ]
